#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Restored deck lists for the V2 simulation (generated from Decks.cs).

The C# Decks.cs has crash-prone cards commented out, leaving 6 of 9 decks
below 30 cards (ZooDiscardWarlock at 11). Auditing Card.Implemented showed
47 of the 49 commented copies ARE implemented; a 150-game stress test of
the restored decks produced zero NotImplementedException. This module
therefore restores every implemented card (original list order).

Deviations from the published archetype lists:
  * Dark Peddler x2 (Zoo) is genuinely unimplemented -> replaced with a
    2nd Abusive Sergeant + 2nd Crazed Alchemist to reach 30 cards.

Decks.cs and the compiled DLL are untouched; decks are built at runtime
via Cards.FromName. Use build_deck(name) for a fresh .NET List[Card].
"""

from System.Collections.Generic import List          # noqa: E402
from SabberStoneCore.Model import Cards, Card        # noqa: E402

DECK_LISTS = {
    "MiraclePirateRogue": [
        "Backstab",
        "Backstab",
        "Counterfeit Coin",
        "Preparation",
        "Preparation",
        "Cold Blood",
        "Cold Blood",
        "Conceal",
        "Conceal",
        "Swashburglar",
        "Eviscerate",
        "Eviscerate",
        "Sap",
        "Sap",
        "Edwin VanCleef",
        "Fan of Knives",
        "Fan of Knives",
        "Tomb Pillager",
        "Tomb Pillager",
        "Patches the Pirate",
        "Small-Time Buccaneer",
        "Small-Time Buccaneer",
        "Bloodmage Thalnos",
        "Questing Adventurer",
        "Questing Adventurer",
        "Azure Drake",
        "Azure Drake",
        "Leeroy Jenkins",
        "Gadgetzan Auctioneer",
        "Gadgetzan Auctioneer",
    ],
    "ZooDiscardWarlock": [
        "Flame Imp",
        "Flame Imp",
        "Malchezaar's Imp",
        "Malchezaar's Imp",
        "Possessed Villager",
        "Possessed Villager",
        "Soulfire",
        "Soulfire",
        "Voidwalker",
        "Voidwalker",
        "Darkshire Librarian",
        "Darkshire Librarian",
        "Darkshire Councilman",
        "Darkshire Councilman",
        "Imp Gang Boss",
        "Imp Gang Boss",
        "Silverware Golem",
        "Silverware Golem",
        "Doomguard",
        "Doomguard",
        "Abusive Sergeant",
        "Crazed Alchemist",
        "Dire Wolf Alpha",
        "Dire Wolf Alpha",
        "Knife Juggler",
        "Knife Juggler",
        "Defender of Argus",
        "Defender of Argus",
        "Abusive Sergeant",
        "Crazed Alchemist",
    ],
    "RenoKazakusDragonPriest": [
        "Northshire Cleric",
        "Potion of Madness",
        "Power Word: Shield",
        "Twilight Whelp",
        "Shadow Word: Pain",
        "Wyrmrest Agent",
        "Kabal Talonpriest",
        "Shadow Word: Death",
        "Priest of the Feast",
        "Drakonid Operative",
        "Holy Nova",
        "Raza the Chained",
        "Cabal Shadow Priest",
        "Dragonfire Potion",
        "Entomb",
        "Acidic Swamp Ooze",
        "Dirty Rat",
        "Doomsayer",
        "Netherspite Historian",
        "Brann Bronzebeard",
        "Kabal Courier",
        "Kazakus",
        "Twilight Drake",
        "Twilight Guardian",
        "Azure Drake",
        "Blackwing Corruptor",
        "Book Wyrm",
        "Reno Jackson",
        "Chillmaw",
        "Ysera",
    ],
    "MidrangeSecretHunter": [
        "Alleycat",
        "Alleycat",
        "Bear Trap",
        "Bear Trap",
        "Explosive Trap",
        "Explosive Trap",
        "Quick Shot",
        "Quick Shot",
        "Scavenging Hyena",
        "Scavenging Hyena",
        "Snake Trap",
        "Snake Trap",
        "Animal Companion",
        "Animal Companion",
        "Cloaked Huntress",
        "Cloaked Huntress",
        "Eaglehorn Bow",
        "Eaglehorn Bow",
        "Kill Command",
        "Kill Command",
        "Unleash the Hounds",
        "Unleash the Hounds",
        "Houndmaster",
        "Houndmaster",
        "Savannah Highmane",
        "Savannah Highmane",
        "Secretkeeper",
        "Secretkeeper",
        "Knife Juggler",
        "Knife Juggler",
    ],
    "MidrangeBuffPaladin": [
        "Smuggler's Run",
        "Smuggler's Run",
        "Argent Lance",
        "Grimestreet Outfitter",
        "Grimestreet Outfitter",
        "Aldor Peacekeeper",
        "Aldor Peacekeeper",
        "Wickerflame Burnbristle",
        "Truesilver Champion",
        "Truesilver Champion",
        "Grimestreet Enforcer",
        "Grimestreet Enforcer",
        "Tirion Fordring",
        "Sir Finley Mrrgglton",
        "Worgen Infiltrator",
        "Worgen Infiltrator",
        "Flame Juggler",
        "Flame Juggler",
        "Acolyte of Pain",
        "Acolyte of Pain",
        "Argent Horserider",
        "Argent Horserider",
        "Sen'jin Shieldmasta",
        "Sen'jin Shieldmasta",
        "Psych-o-Tron",
        "Second-Rate Bruiser",
        "Second-Rate Bruiser",
        "Argent Commander",
        "Argent Commander",
        "Don Han'Cho",
    ],
    "MurlocDruid": [
        "Innervate",
        "Innervate",
        "Enchanted Raven",
        "Enchanted Raven",
        "Living Roots",
        "Living Roots",
        "Druid of the Saber",
        "Druid of the Saber",
        "Mark of Y'Shaarj",
        "Mark of Y'Shaarj",
        "Savage Roar",
        "Savage Combatant",
        "Savage Combatant",
        "Swipe",
        "Swipe",
        "Druid of the Claw",
        "Druid of the Claw",
        "Sir Finley Mrrgglton",
        "Bluegill Warrior",
        "Bluegill Warrior",
        "Faerie Dragon",
        "Faerie Dragon",
        "Murloc Warleader",
        "Murloc Warleader",
        "Zoobot",
        "Zoobot",
        "Azure Drake",
        "Azure Drake",
        "Finja, the Flying Star",
        "The Curator",
    ],
    "MidrangeJadeShaman": [
        "Tunnel Trogg",
        "Tunnel Trogg",
        "Totem Golem",
        "Totem Golem",
        "Thing from Below",
        "Thing from Below",
        "Spirit Claws",
        "Spirit Claws",
        "Maelstrom Portal",
        "Maelstrom Portal",
        "Lightning Storm",
        "Lightning Bolt",
        "Jade Lightning",
        "Jade Lightning",
        "Jade Claws",
        "Jade Claws",
        "Hex",
        "Hex",
        "Flametongue Totem",
        "Flametongue Totem",
        "Al'Akir the Windlord",
        "Patches the Pirate",
        "Small-Time Buccaneer",
        "Small-Time Buccaneer",
        "Bloodmage Thalnos",
        "Barnes",
        "Azure Drake",
        "Azure Drake",
        "Aya Blackpaw",
        "Ragnaros the Firelord",
    ],
    "AggroPirateWarrior": [
        "Sir Finley Mrrgglton",
        "Fiery War Axe",
        "Fiery War Axe",
        "Heroic Strike",
        "Heroic Strike",
        "N'Zoth's First Mate",
        "N'Zoth's First Mate",
        "Upgrade!",
        "Upgrade!",
        "Bloodsail Cultist",
        "Bloodsail Cultist",
        "Frothing Berserker",
        "Frothing Berserker",
        "Kor'kron Elite",
        "Kor'kron Elite",
        "Arcanite Reaper",
        "Arcanite Reaper",
        "Patches the Pirate",
        "Small-Time Buccaneer",
        "Small-Time Buccaneer",
        "Southsea Deckhand",
        "Southsea Deckhand",
        "Bloodsail Raider",
        "Bloodsail Raider",
        "Southsea Captain",
        "Southsea Captain",
        "Dread Corsair",
        "Dread Corsair",
        "Naga Corsair",
        "Naga Corsair",
    ],
    "RenoKazakusMage": [
        "Forbidden Flame",
        "Arcane Blast",
        "Babbling Book",
        "Frostbolt",
        "Arcane Intellect",
        "Forgotten Torch",
        "Ice Barrier",
        "Ice Block",
        "Manic Soulcaster",
        "Volcanic Potion",
        "Fireball",
        "Polymorph",
        "Water Elemental",
        "Cabalist's Tome",
        "Blizzard",
        "Firelands Portal",
        "Flamestrike",
        "Acidic Swamp Ooze",
        "Bloodmage Thalnos",
        "Dirty Rat",
        "Doomsayer",
        "Brann Bronzebeard",
        "Kabal Courier",
        "Mind Control Tech",
        "Kazakus",
        "Refreshment Vendor",
        "Azure Drake",
        "Reno Jackson",
        "Sylvanas Windrunner",
        "Alexstrasza",
    ],
}


def build_deck(deck_name):
    """Fresh .NET List[Card] for one deck (validates every name)."""
    lst = List[Card]()
    for name in DECK_LISTS[deck_name]:
        card = Cards.FromName(name)
        if card is None:
            raise ValueError("unknown card %r in deck %s" % (name, deck_name))
        if not bool(card.Implemented):
            raise ValueError("unimplemented card %r in deck %s" % (name, deck_name))
        lst.Add(card)
    return lst
