# -*- coding: utf-8 -*-
"""Bring the *non-reviewer* N-sweep sections in line with the reviewer follow-ups:

  * §6 (cluster-ARI vs N), §8 (games-to-classify vs N) and the V4 cross-deck
    aggregation cell now all sweep the SAME N grid as Reviewer #2/#3b, and
  * their x-axis is plotted on equally-spaced categorical positions labelled by
    each N value (no log scale / power-of-10 ticks).

Targeted by cell id so the reviewer cells (regenerated by _append_reviewer_graphs.py)
are never touched.  Each replacement is asserted, so a silent template drift fails loudly.
Outputs of edited cells are cleared (the old figures are stale).

Run:  py -3 Log_Analysis/_patch_N_sweeps.py
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
NEW_LIST  = "[1, 2, 3, 5, 8, 10, 15, 20, 25, 35, 50, 70, 90, 100, 120]"
NEW_TUPLE = "(1, 2, 3, 5, 8, 10, 15, 20, 25, 35, 50, 70, 90, 100, 120)"

NOTEBOOKS = [
    "V1/playstyle_log_distribution_analysis_AggroPirateWarrior.ipynb",
    "V1/playstyle_log_distribution_analysis_RenoKazakusMage.ipynb",
    "V2/playstyle_log_distribution_analysis_RenoKazakusMage_v2.ipynb",
    "V3/playstyle_log_distribution_analysis_RenoKazakusMage_v3.ipynb",
    "V3/playstyle_log_distribution_analysis_RenoKazakusMage_v3_full.ipynb",
    "V4/playstyle_log_distribution_analysis_RenoKazakusMage_v4.ipynb",
]

# id -> list of (old, new) replacements applied to that cell's joined source.
# §6 ids: 5cf70b12 (all) / 75c2c3f5 (W1) ; §8 ids: 74d23828 (all) / 51beabc1 (W1)
SECTION6 = [
    ("Ns = [1, 5, 10, 20, 40, 80, 150, 300]",
     "Ns = " + NEW_LIST),
    ('ax[0].plot(Ns, aris, "o-", label="cluster–style ARI")\n'
     'ax[0].plot(Ns, sils, "s--", color="gray", label="silhouette")\n'
     'ax[0].set_xscale("log"); ax[0].set_xlabel("games averaged per fingerprint (N)")',
     '_xs = range(len(Ns))\n'
     'ax[0].plot(_xs, aris, "o-", label="cluster–style ARI")\n'
     'ax[0].plot(_xs, sils, "s--", color="gray", label="silhouette")\n'
     'ax[0].set_xticks(list(_xs)); ax[0].set_xticklabels(Ns, rotation=45)\n'
     'ax[0].set_xlabel("games averaged per fingerprint (N)")'),
]
SECTION8 = [
    ("Ns = [1, 2, 3, 5, 8, 12, 20, 30, 50, 80, 120]",
     "Ns = " + NEW_LIST),
    ('for s in STYLE_ORDER:\n'
     '    ax[0].plot(acc.index, acc[s], "o-", color=STYLE_COLORS[s], label=s)\n'
     'ax[0].plot(acc.index, acc["overall (LDA)"], "k--", lw=2, label="overall")',
     '_xs = range(len(acc.index))\n'
     'for s in STYLE_ORDER:\n'
     '    ax[0].plot(_xs, acc[s], "o-", color=STYLE_COLORS[s], label=s)\n'
     'ax[0].plot(_xs, acc["overall (LDA)"], "k--", lw=2, label="overall")'),
    ('ax[0].set_xscale("log"); ax[0].set_ylim(0, 1.02); ax[0].set_xlabel("games averaged per fingerprint (N)")',
     'ax[0].set_xticks(list(_xs)); ax[0].set_xticklabels(acc.index, rotation=45); '
     'ax[0].set_ylim(0, 1.02); ax[0].set_xlabel("games averaged per fingerprint (N)")'),
]
V4XDECK = [
    ("Ns=(1, 2, 3, 5, 8, 12, 20, 30, 50, 80, 120)",
     "Ns=" + NEW_TUPLE),
    ('    s = (cross_agg(feats, DA, DB) + cross_agg(feats, DB, DA)) / 2\n'
     '    ax.plot(s.index, s.values, marker="o", label=name)',
     '    s = (cross_agg(feats, DA, DB) + cross_agg(feats, DB, DA)) / 2\n'
     '    _xs = range(len(s.index)); ax.plot(_xs, s.values, marker="o", label=name)'),
    ('ax.set_xscale("log"); ax.set_xlabel("games pooled into one cross-deck fingerprint (N)")',
     'ax.set_xticks(list(_xs)); ax.set_xticklabels(s.index, rotation=45); '
     'ax.set_xlabel("games pooled into one cross-deck fingerprint (N)")'),
]

CELL_PATCHES = {
    "5cf70b12": SECTION6, "75c2c3f5": SECTION6,
    "74d23828": SECTION8, "51beabc1": SECTION8,
    "v4xdeck_agg": V4XDECK,
}


def patch(rel):
    path = os.path.join(HERE, rel)
    nb = json.load(open(path, encoding="utf-8"))
    changed = 0
    for c in nb["cells"]:
        reps = CELL_PATCHES.get(c.get("id"))
        if c["cell_type"] != "code" or not reps:
            continue
        text = orig = "".join(c["source"])
        for old, new in reps:
            if old in text:
                text = text.replace(old, new)
            else:                                   # idempotent: already migrated?
                assert new in text, f"{rel} cell {c['id']}: pattern not found:\n{old[:60]!r}"
        if text == orig:
            continue
        c["source"] = text.splitlines(keepends=True)
        c["outputs"] = []           # old figure is stale -> force a re-run
        c["execution_count"] = None
        changed += 1
    json.dump(nb, open(path, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    print(f"patched {rel:64s} {changed} cell(s)")


if __name__ == "__main__":
    for rel in NOTEBOOKS:
        patch(rel)
    print("done.")
